version: "3"

services:
  db:
    image: "mysql:8.0.32"
    ports:
      - 3306:3306
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/amd64
  app:
    build:
      context: ./app
    volumes:
      - ../src:/work/backend
    depends_on: ["db"]

  web:
    build:
      context: ./web
    ports:
      - 80:80
    volumes:
      - ../src:/work/backend
    depends_on: ["app"]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1024:1025"
      - "8024:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=laravel
      - PMA_PASSWORD=password
    ports:
      - "3000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions